language: julia
os:
  - linux
  - windows
  - osx

julia:
  - 1.2
  # - nightly # commented to save energy and time

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"
  - julia -e 'using Pkg; ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.build(); Pkg.add("PyPlot")'


matrix:
  allow_failures:
  - julia: nightly

notifications:
  email:
    on_success: never
    on_failure: never
